# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/contracts.ipynb (unless otherwise specified).

__all__ = ['short', 'Address', 'Token', 'Contract', 'OBJTYPES', 'ALL_ADDRESSES', 'make_from_entry', 'BY_ADDRESS',
           'BY_NAME', 'whatis']

# Cell

import pandas as pd
import numpy as np
from pydantic import BaseModel, validator

def short(address):
    return address[:5]+'…'+address[-4:]

class Address(BaseModel):
    objtype:str
    prefix:str
    name: str
    address:str

    @validator('prefix')
    def prefix_is_not_nan(cls, prefix_str):
        if prefix_str == 'nan':
            return ''
        return prefix_str
    @validator('address')
    def address_is_lower(cls, address_str):
        return address_str.lower()
    def desc(self):
        if self.prefix:
            return '{pre}_{n}'.format(pre=self.prefix, n=self.name)
        else:
            return self.name

    def __repr__(self):
        return str(self)
    def __str__(self):
        return '<{objtype} {d}:{sa}>'.format(objtype=self.objtype,
                                             d=self.desc(),
                                             sa=short(self.address))

class Token(Address):
    pass

class Contract(Address):
    pass

OBJTYPES = {'TOKEN': Token,
           'CONTRACT': Contract,
            'ADDRESS': Address
           }


# Cell
ALL_ADDRESSES = [
    {
        "address": "0x5A0D867E0D70FCC6ADE25C3F1B89D618B5B4EAA7",
        "name": "sovrynProtocol",
        "objtype": "Contract",
        "prefix": ""
    },
    {
        "address": "0x437AC62769F386B2D238409B7F0A7596D36506E4",
        "name": "priceFeeds",
        "objtype": "Contract",
        "prefix": "margin"
    },
    {
        "address": "0xF515B17624A89C8D71E06D587ECD68F60E5CA2C8",
        "name": "SwapsImpl",
        "objtype": "Contract",
        "prefix": "margin"
    },
    {
        "address": "0x61D553223161759361FE0DF82A993D2415E69984",
        "name": "ProtocolSettings",
        "objtype": "Contract",
        "prefix": "margin"
    },
    {
        "address": "0x62D4BA66721FD14007A1C49290EA4BE005B1C0B8",
        "name": "LoanSettings",
        "objtype": "Contract",
        "prefix": "margin"
    },
    {
        "address": "0xC51D22C296746202527509BE68F949CF8C72F2BF",
        "name": "LoanOpenings",
        "objtype": "Contract",
        "prefix": "margin"
    },
    {
        "address": "0x7CFBAA1017A419AEFD1240B24E8D781CE62FE3D8",
        "name": "LoanMaintenance",
        "objtype": "Contract",
        "prefix": "margin"
    },
    {
        "address": "0x49ECDCCC0B52F306307168DC765E904A739F4770",
        "name": "LoanClosings",
        "objtype": "Contract",
        "prefix": "margin"
    },
    {
        "address": "0x9B75DBF670774451639CBC0E6F5792D8AB4F72E2",
        "name": "SwapsExternal",
        "objtype": "Contract",
        "prefix": "margin"
    },
    {
        "address": "0xE700691DA7B9851F2F35F8B8182C69C53CCAD9DB",
        "name": "DoC",
        "objtype": "Token",
        "prefix": ""
    },
    {
        "address": "0x542FDA317318EBF1D3DEAF76E0B632741A7E677D",
        "name": "WRBTC",
        "objtype": "Token",
        "prefix": ""
    },
    {
        "address": "0xEF213441A85DF4D7ACBDAE0CF78004E1E486BB96",
        "name": "USDT",
        "objtype": "Token",
        "prefix": ""
    },
    {
        "address": "0x440CD83C160DE5C96DDB20246815EA44C7ABBCA8",
        "name": "BPRO",
        "objtype": "Token",
        "prefix": ""
    },
    {
        "address": "0x1D931BF8656D795E50EF6D639562C5BD8AC2B78F",
        "name": "ETHs",
        "objtype": "Token",
        "prefix": ""
    },
    {
        "address": "0x9AC7FE28967B30E3A4E6E03286D715B42B453D10",
        "name": "MOC",
        "objtype": "Token",
        "prefix": ""
    },
    {
        "address": "0xB5999795BE0EBB5BAB23144AA5FD6A02D080299F",
        "name": "XUSD",
        "objtype": "Token",
        "prefix": ""
    },
    {
        "address": "0xD8D25F03EBBA94E15DF2ED4D6D38276B595593C1",
        "name": "LoanToken",
        "objtype": "Token",
        "prefix": "iDOC"
    },
    {
        "address": "0x52235977526BD661F6FD518DFD2FC2F335F14424",
        "name": "LoanTokenLogic",
        "objtype": "Contract",
        "prefix": "iDOC"
    },
    {
        "address": "0xA9DCDC63EABB8A2B6F39D7FF9429D88340044A7A",
        "name": "LoanToken",
        "objtype": "Token",
        "prefix": "iRBTC"
    },
    {
        "address": "0x0E3816F348CB2AEEEF1976ACFFD8E078D4A9878A",
        "name": "LoanTokenLogic",
        "objtype": "Contract",
        "prefix": "iRBTC"
    },
    {
        "address": "0x849C47F9C259E9D62F289BF1B2729039698D8387",
        "name": "LoanToken",
        "objtype": "Token",
        "prefix": "iUSDT"
    },
    {
        "address": "0x52235977526BD661F6FD518DFD2FC2F335F14424",
        "name": "LoanTokenLogic",
        "objtype": "Contract",
        "prefix": "iUSDT"
    },
    {
        "address": "0x6E2FB26A60DA535732F8149B25018C9C0823A715",
        "name": "LoanToken",
        "objtype": "Token",
        "prefix": "iBPRo"
    },
    {
        "address": "0x52235977526BD661F6FD518DFD2FC2F335F14424",
        "name": "LoanTokenLogic",
        "objtype": "Contract",
        "prefix": "iBPRo"
    },
    {
        "address": "0x8F77ECF69711A4B346F23109C40416BE3DC7F129",
        "name": "LoanToken",
        "objtype": "Token",
        "prefix": "iXUSD"
    },
    {
        "address": "0x98ACE08D2B759A265AE326F010496BCD63C15AFC",
        "name": "Network",
        "objtype": "Contract",
        "prefix": "SWAP_AMM"
    },
    {
        "address": "0xA917BF723433D020A15629EBA71F6C2A6B38E52D",
        "name": "RBTC Wrapper",
        "objtype": "Contract",
        "prefix": "SWAP_AMM"
    },
    {
        "address": "0xD715192612F03D20BAE53A5054AF530C9BB0FA3F",
        "name": "Swap Converter",
        "objtype": "Contract",
        "prefix": "Swap_DoC"
    },
    {
        "address": "0x2DC80332C19FBCD5169AB4A579D87EE006CB72C0",
        "name": "DoC Pool Share Token",
        "objtype": "Contract",
        "prefix": "Swap_DoC"
    },
    {
        "address": "0x840437BDE7346EC13B5451417DF50586F4DAF836",
        "name": "BTC Pool Share Token",
        "objtype": "Contract",
        "prefix": "Swap_DoC"
    },
    {
        "address": "0x448C2474B255576554EED36C24430CCFAC131CE3",
        "name": "Swap Converter",
        "objtype": "Contract",
        "prefix": "Swap USDT"
    },
    {
        "address": "0x40580E31CC14DBF7A0859F38AB36A84262DF821D",
        "name": "USDT Pool Share Token",
        "objtype": "Contract",
        "prefix": "Swap USDT"
    },
    {
        "address": "0x9C4017D1C04CFA0F97FDC9505E33A0D8AC84817F",
        "name": "BTC Pool Share Token",
        "objtype": "Contract",
        "prefix": "Swap USDT"
    },
    {
        "address": "0x26463990196B74AD5644865E4D4567E4A411E065",
        "name": "Swap Converter",
        "objtype": "Contract",
        "prefix": "Swap BPro"
    },
    {
        "address": "0x9CE25371426763025C04A9FCD581FBB9E4593475",
        "name": "BPro Pool Share Token",
        "objtype": "Contract",
        "prefix": "Swap BPro"
    },
    {
        "address": "0x75E327A83AD2BFD53DA12EB718FCCFC68BC57535",
        "name": "BTC Pool Share Token",
        "objtype": "Contract",
        "prefix": "Swap BPro"
    },
    {
        "address": "0x1D2C04967E8B17168310FD7035CC219DE477BE82",
        "name": "Swap Converter",
        "objtype": "Contract",
        "prefix": "Swap SOV"
    },
    {
        "address": "0x09C5FAF7723B13434ABDF1A65AB1B667BC02A902",
        "name": "Pool Token",
        "objtype": "Contract",
        "prefix": "Swap SOV"
    },
    {
        "address": "0x22FC2CEE6DC31E29DCB68F1DA77718C687551A20",
        "name": "Swap Converter",
        "objtype": "Contract",
        "prefix": "Swap ETH"
    },
    {
        "address": "0xF41ED702DF2B84ACE02772C6A0D8AE46465AA5F4",
        "name": "Pool Token",
        "objtype": "Contract",
        "prefix": "Swap ETH"
    },
    {
        "address": "0x52ED2AD69A44A431B393D28CE415C19348ABAB16",
        "name": "Swap Converter",
        "objtype": "Contract",
        "prefix": "Swap MOC"
    },
    {
        "address": "0x7FEF930EBAA90B2F8619722ADC55E3F1D965B79B",
        "name": "Pool Token",
        "objtype": "Contract",
        "prefix": "Swap MOC"
    },
    {
        "address": "0xF90558859D1BBC79544CB2DA49BA7CE471A6343E",
        "name": "Swap Converter",
        "objtype": "Contract",
        "prefix": "Swaps BNB"
    },
    {
        "address": "0x8F3D24AB3510294F1466AA105F78901B90D79D4D",
        "name": "Pool token",
        "objtype": "Contract",
        "prefix": "Swaps BNB"
    },
    {
        "address": "0x303401D9AB4394AEAE4156F1A21C620EED56E22C",
        "name": "Swap Converter",
        "objtype": "Contract",
        "prefix": "Swaps XUSD"
    },
    {
        "address": "0x6F96096687952349DD5944E0EB1BE327DCDEB705",
        "name": "Pool token",
        "objtype": "Contract",
        "prefix": "Swaps XUSD"
    },
    {
        "address": "0xE4D2E26CE947DF7A8D04E5A9DCDEF0C540C497CF",
        "name": "BPro",
        "objtype": "Contract",
        "prefix": "Swap Oracles"
    },
    {
        "address": "0x46EBC03EF2277308BDB106A73D11C65109C4B89B",
        "name": "ContractRegistry",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0xCF46F24423B8DA97E2C06B41DF28163D55E80935",
        "name": "ConverterFactory",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0x3278734B16F27ED5C69FD246DF9357A866FD811E",
        "name": "sovrynSwapFormula",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0xAD3376BE8DF32BB00DF4C4402E6662C630167D62",
        "name": "ConversionPathFinder",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0x40346F7CE14B3A10BAB22F6A0A444902CF0BC598",
        "name": "ConverterUpgrader",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0x31A0F8400C75D52FDB413372233F28E3BDFB1C06",
        "name": "ConverterRegistry",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0x73EEF416CB8B63DBFCC66719F0B74BB7BAEA48FE",
        "name": "converterRegistryData",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0x7CE4B812F4B2115135215FFA48D3B6F60F75CB52",
        "name": "LiquidTokenConverterFactory",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0x812B156BFD6FA7C4C86D26E6699A82F75FA5AAEB",
        "name": "LiquidityPoolV1ConverterFactory",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0x846F005F7587F24822D51B7072906F558EE9FEB5",
        "name": "liquidityPoolV2ConverterFactory",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0xE93726E74EEF8097E49C1AAB7879F91B95FA02E8",
        "name": "LiquidityPoolV2ConverterAnchorFactory",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0x5204E8BAA485F9511BE3943EBEA3E4AF07BDAFEF",
        "name": "liquidityPoolV2ConverterCustomFactory",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0x8E75774EF928CE730255AB594DD1B9F0A725A56B",
        "name": "oracleWhitelist",
        "objtype": "Contract",
        "prefix": "other_AMM"
    },
    {
        "address": "0x391FE8A92A7FC626A25F30E8C19B92BF8BE37FD3",
        "name": "priceFeedsMoc (WRBTC)",
        "objtype": "Contract",
        "prefix": "PriceFeeds"
    },
    {
        "address": "0xED80CCDE8BAEFF2DBFC70D3028A27E501FA0D7D5",
        "name": "USDT PriceFeed",
        "objtype": "Contract",
        "prefix": "PriceFeeds"
    },
    {
        "address": "0x389E2447E1397A8E485D658A44D845A324A338CF",
        "name": "BPro PriceFeed",
        "objtype": "Contract",
        "prefix": "PriceFeeds"
    },
    {
        "address": "0x54C33CB8A3A32A716BEC40C3CEB5BA8B0FB92A57",
        "name": "WRBTC PriceFeed (RSK)",
        "objtype": "Contract",
        "prefix": "PriceFeeds"
    },
    {
        "address": "0xB9C42EFC8EC54490A37CA91C423F7285FA01E257",
        "name": "MoC State",
        "objtype": "Contract",
        "prefix": "PriceFeeds"
    },
    {
        "address": "0x924F5AD34698FD20C90FE5D5A8A0ABD3B42DC711",
        "name": "exchequer multisig",
        "objtype": "Contract",
        "prefix": "MS"
    },
    {
        "address": "0x576AE218AECFD4CBD2DBE07250B47E26060932B1",
        "name": "OG EarlyAccessToken",
        "objtype": "Contract",
        "prefix": "NFTS"
    },
    {
        "address": "0x857A62C9C0B6F1211E04275A1F0C5F26FCE2021F",
        "name": "Genesis Community Tier",
        "objtype": "Contract",
        "prefix": "NFTS"
    },
    {
        "address": "0x7806D3FEDF9C9741041F5D70AF5ADF326705B03D",
        "name": "Genesis Hero Tier",
        "objtype": "Contract",
        "prefix": "NFTS"
    },
    {
        "address": "0xD9BBCD6E0AB105C83E2B5BE0BBB9BB90EF963DE7",
        "name": "Genesis Super Hero Tier",
        "objtype": "Contract",
        "prefix": "NFTS"
    },
    {
        "address": "0xC8CBDB42CE55BDEE96D6425396E4047EE46F2E37",
        "name": "NTSOV",
        "objtype": "Contract",
        "prefix": "Governance 1.0"
    },
    {
        "address": "0xCE3A21A69C05CFE638B722F53593A047BDD6E9DE",
        "name": "governor",
        "objtype": "Contract",
        "prefix": "Governance 1.1"
    },
    {
        "address": "0x04CB2EF013F866E9915016E44FE36218361C1F5A",
        "name": "timelock",
        "objtype": "Contract",
        "prefix": "Governance 1.2"
    },
    {
        "address": "0xC7A1637B37190A456B017897207BCEB2A29F19B9",
        "name": "governorVault",
        "objtype": "Contract",
        "prefix": "Governance 1.3"
    },
    {
        "address": "0x1B1656CBEF05522184F833B5CA9405072DAA8416",
        "name": "MultiSigKeyHolders",
        "objtype": "Contract",
        "prefix": "Governance 1.4"
    },
    {
        "address": "0x0106F2FFBF6A4F5DECE323D20E16E2037E732790",
        "name": "CSOVToken",
        "objtype": "Token",
        "prefix": "Genesis Sale"
    },
    {
        "address": "0xD42070B07D4EABB801D76C6929F21749647275EC",
        "name": "CrowdSale",
        "objtype": "Contract",
        "prefix": "Genesis Sale"
    },
    {
        "address": "0x7F7DCF9DF951C4A332740E9A125720DA242A34FF",
        "name": "CSOV2",
        "objtype": "Contract",
        "prefix": "Genesis Sale"
    },
    {
        "address": "0xEFC78FC7D48B64958315949279BA181C2114ABBD",
        "name": "SOV",
        "objtype": "Token",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x5684A06CAB22DB16D901FEE2A5C081B4C91EA40E",
        "name": "Staking:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x12B1B0C67D9A771EB5DB7726D23FDC6848FD93EF",
        "name": "FeeSharingProxy:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x967C84B731679E36A344002B8E3CE50620A7F69F",
        "name": "TimelockOwner:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x6496DF39D000478A7A7352C01E0E713835051CCD",
        "name": "GovernorOwner:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x05F4F068DF59A5AA7911F57CE4F41EBFBCB8E247",
        "name": "GovernorVaultOwner:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x6C94C8AA97C08FC31FB06FBFDA90E1E09529FB13",
        "name": "TimelockAdmin:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0xFF25F66B7D7F385503D70574AE0170B6B1622DAD",
        "name": "GovernorAdmin:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x51C754330C6CD04B810014E769DAB0343E31409E",
        "name": "GovernorVaultAdmin:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x24FBA2281202C3AAE95A3440C08C0050448508A6",
        "name": "VestingLogic:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x80B036AE59B3E38B573837C01BB1DB95515B7E6B",
        "name": "VestingRegistry:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x0F31CFD6AAB4D378668AD74DEFA89D3F4DB26633",
        "name": "AdoptionFund:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x617866CC4A089C3653DDC31A618B078291839AEB",
        "name": "DevelopmentFund:",
        "objtype": "Contract",
        "prefix": "Governance 2.0"
    },
    {
        "address": "0x0F279E810B95E0D425622B9B40D7BCD0B5C4B19D",
        "name": "Multisig",
        "objtype": "Contract",
        "prefix": "FastBTC"
    },
    {
        "address": "0xCA1C5B1BC55755C5E3B6ED1AFE88ABD7B26F147F",
        "name": "ManagedWallet",
        "objtype": "Contract",
        "prefix": "FastBTC"
    },
    {
        "address": "0xB4E4517CA4EDF591DCAFB702999F04F02E57D978",
        "name": "LockedSOV",
        "objtype": "Contract",
        "prefix": "Liquidity Mining"
    },
    {
        "address": "0xBD50232E6FBFA43C95062D1A9D6ECF5439906C21",
        "name": "LiquidityMining (Logic)",
        "objtype": "Contract",
        "prefix": "Liquidity Mining"
    },
    {
        "address": "0xF730AF26E87D9F55E46A6C447ED2235C385E55E0",
        "name": "LiquidityMiningProxy",
        "objtype": "Contract",
        "prefix": "Liquidity Mining"
    },
    {
        "address": "0x33C0D33A0D4312562AD622F91D12B0AC47366EE1",
        "name": "Bridge",
        "objtype": "Contract",
        "prefix": "Bridge ETH-RSK, ETH SIDE"
    },
    {
        "address": "0x2493B92B3B958C8D1E93899CAE00BFC4854CBD18",
        "name": "federation",
        "objtype": "Contract",
        "prefix": "Bridge ETH-RSK, ETH SIDE"
    },
    {
        "address": "0x062C74F9D27B1178BB76186C1756128CCB3CCD2E",
        "name": "multiSig",
        "objtype": "Contract",
        "prefix": "Bridge ETH-RSK, ETH SIDE"
    },
    {
        "address": "0x8DF20C2C85BEE0C3DA250DA96D892598C70AA1BE",
        "name": "allowTokens",
        "objtype": "Contract",
        "prefix": "Bridge ETH-RSK, ETH SIDE"
    },
    {
        "address": "0xD412ACD34A832A09C80C8A4895FF46D733F09538",
        "name": "WETH (Bridge internal)",
        "objtype": "Contract",
        "prefix": "Bridge ETH-RSK, ETH SIDE"
    },
    {
        "address": "0xBDAB72602E9AD40FC6A6852CAF43258113B8F7A5",
        "name": "eSOV",
        "objtype": "Contract",
        "prefix": "Bridge ETH-RSK, ETH SIDE"
    },
    {
        "address": "0x1CCAD820B6D031B41C54F1F3DA11C0D48B399581",
        "name": "Bridge",
        "objtype": "Contract",
        "prefix": "Bridge ETH-RSK, RSK SIDE"
    },
    {
        "address": "0x99896B7E917FF9C130BB86CDE0D778BE37E3464C",
        "name": "federation",
        "objtype": "Contract",
        "prefix": "Bridge ETH-RSK, RSK SIDE"
    },
    {
        "address": "0xB64322E10B5AE1BE121B8BB0DEAD560C53D9DBC3",
        "name": "multiSig",
        "objtype": "Contract",
        "prefix": "Bridge ETH-RSK, RSK SIDE"
    },
    {
        "address": "0xD2090FE759613C3A3E2962C6BB2AD046F62D32FF",
        "name": "allowTokens",
        "objtype": "Contract",
        "prefix": "Bridge ETH-RSK, RSK SIDE"
    },
    {
        "address": "0xFE878227C8F334038DAB20A99FC3B373FFE0A755",
        "name": "ETHes",
        "objtype": "Contract",
        "prefix": "Bridge ETH-RSK, RSK SIDE"
    },
    {
        "address": "0xDFC7127593C8AF1A17146893F10E08528F4C2AA7",
        "name": "Bridge",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, BSC SIDE"
    },
    {
        "address": "0xFC321356BB2CA3D68FAFE9515C24C9B23B63A6A6",
        "name": "federation",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, BSC SIDE"
    },
    {
        "address": "0xEC3FABC3517E64E07669DD1D2D673F466F93A328",
        "name": "multiSig",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, BSC SIDE"
    },
    {
        "address": "0x05B68E70168E876B2025F837BC8E0B2312D5327D",
        "name": "allowTokens",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, BSC SIDE"
    },
    {
        "address": "0xB6C313A427FA911A4C9A119E80FEEA0FE20E69F0",
        "name": "WBNB (Bridge internal)",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, BSC SIDE"
    },
    {
        "address": "0x8753EDE1B3A36358E4D7780F384F3F7A2D9E4359",
        "name": "bSOV",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, BSC SIDE"
    },
    {
        "address": "0x971B97C8CC82E7D27BC467C2DC3F219C6EE2E350",
        "name": "Bridge",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, RSK SIDE"
    },
    {
        "address": "0xC4B5178CC086E764568ADFB2DACCBB0D973E8132",
        "name": "federation",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, RSK SIDE"
    },
    {
        "address": "0xEE9EA57555D9533D71F6F77E0E480961F068A6C5",
        "name": "multiSig",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, RSK SIDE"
    },
    {
        "address": "0xA2F50A2C699C1AA3B9089F6B565D4999D45D8983",
        "name": "allowTokens",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, RSK SIDE"
    },
    {
        "address": "0xD2A826B78200C8434B957913CE4067E6E3169385",
        "name": "BNBbs",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, RSK SIDE"
    },
    {
        "address": "0x30D1B36924C2C0CD1C03EC257D7FFF31BD8C3007",
        "name": "ETHbs",
        "objtype": "Contract",
        "prefix": "Bridge BSC-RSK, RSK SIDE"
    },
    {
        "address": "0x1440D19436BEEAF8517896BFFB957A88EC95A00F",
        "name": "xusd",
        "objtype": "Contract",
        "prefix": "aggregators"
    },
    {
        "address": "0x4BF113905D7F69202106F613308BB02C84AADF2F",
        "name": "eths",
        "objtype": "Contract",
        "prefix": "aggregators"
    },
    {
        "address": "0xAFD905FE2EDBF5A7367A73B0F1E6A62CB5E27D3E",
        "name": "bnbs",
        "objtype": "Contract",
        "prefix": "aggregators"
    }
]

# Cell

def make_from_entry(entry):
    objtype = entry['objtype'].upper()
    objclass = OBJTYPES[objtype]
    return objclass(**entry)

_made_objects = [make_from_entry(addy) for addy in ALL_ADDRESSES]

# Cell
BY_ADDRESS = {e.address:e for e in _made_objects if e is not None}
BY_NAME = {e.name:e for e in _made_objects if e is not None}

# Cell
def whatis(search):
    return [BY_ADDRESS[address] for address in BY_ADDRESS if search.lower() in address]